#pragma once

#include <cstddef>
#include <cstdint>
#include <deque>
#include <functional>
#include <map>
#include <memory>
#include <string>
#include <unordered_map>
#include <vector>

#include "tiny_llm/runtime/processors.h"

namespace tiny_llm {

class KVCache;
struct EngineArgs;

/**
 * @brief Core-only sequence state for token execution and KV bookkeeping.
 */
struct CoreSequence {
    uint64_t internal_id = 0;
    int32_t core_seq_id = -1;
    uint64_t arrival_order = 0;
    std::vector<int32_t> token_ids;
    std::vector<int32_t> block_table;
    SamplingParams sampling_params;
    int32_t generated_tokens = 0;
    int32_t num_computed = 0;
    bool kv_started = false;
    bool finished = false;
};

enum class SchedulerPolicy {
    kFcfs = 0,
};

/**
 * @brief Config-driven scheduler settings.
 */
struct SchedulerConfig {
    SchedulerPolicy policy = SchedulerPolicy::kFcfs;
    size_t max_running_requests = 0; // 0 means no explicit limit
    bool enable_preemption = true;
    int32_t max_prefill_tokens_per_step = 256;
};

/**
 * @brief Metadata consumed by scheduler strategies.
 */
struct SchedulerRequestMeta {
    uint64_t internal_id = 0;
    uint64_t arrival_order = 0;
    int32_t prompt_tokens = 0;
    int32_t num_computed = 0;
};

/**
 * @brief Executable task selected by the scheduler for current step.
 */
struct ScheduleTask {
    uint64_t internal_id = 0;
    bool is_prefill = false;
    int32_t num_tokens_to_process = 0;
};

/**
 * @brief Scheduler outputs for this schedule cycle.
 */
struct SchedulerResult {
    std::vector<ScheduleTask> tasks;
    std::vector<uint64_t> preempted_ids;
};

/**
 * @brief Runtime execution descriptor generated by scheduler for one task.
 */
struct SchedulerTaskDescriptor {
    uint64_t internal_id = 0;
    int32_t core_seq_id = -1;
    bool is_prefill = false;
    int32_t start_position = 0;
    std::vector<int32_t> token_ids;
};

/**
 * @brief Scheduler output package for one runtime step.
 */
struct SchedulerOutput {
    std::vector<SchedulerTaskDescriptor> tasks;
    std::vector<uint64_t> preempted_ids;
};

/**
 * @brief Per-task execution result returned by ModelExecutor stage.
 */
struct ModelTaskOutput {
    uint64_t internal_id = 0;
    bool is_prefill = false;
    int32_t processed_tokens = 0;
    int32_t sampled_token_id = -1;
    bool has_error = false;
    std::string error_message;
};

/**
 * @brief Aggregated model execution results for one runtime step.
 */
struct ModelOutput {
    std::vector<ModelTaskOutput> tasks;
};

/**
 * @brief KV block estimation and block table refresh helper for scheduler/runtime.
 */
class BlockManager {
public:
    explicit BlockManager(KVCache* kv);
    BlockManager(int32_t kv_num_layers,
                 int32_t kv_block_size_tokens,
                 size_t kv_num_blocks,
                 size_t kv_block_size_bytes,
                 void* kv_memory_pool);
    ~BlockManager();

    size_t free_block_count() const;
    int32_t num_layers() const;
    KVCache* kv_cache() const { return kv_; }

    void start_sequence(int32_t core_seq_id) const;
    void end_sequence(int32_t core_seq_id) const;

    size_t estimate_append_new_blocks(
        int32_t core_seq_id,
        bool kv_started,
        int32_t num_computed) const;

    size_t estimate_prefill_new_blocks(
        int32_t core_seq_id,
        bool kv_started,
        int32_t prompt_tokens,
        int32_t num_computed,
        int32_t prefill_tokens) const;

    void refresh_block_table(
        int32_t core_seq_id,
        bool kv_started,
        std::vector<int32_t>& block_table) const;

private:
    std::unique_ptr<KVCache> owned_kv_;
    KVCache* kv_ = nullptr;
};

/**
 * @brief Strategy interface for waiting-queue ordering and preemption choice.
 */
class SchedulerStrategy {
public:
    virtual ~SchedulerStrategy() = default;

    virtual void sort_waiting(
        std::deque<uint64_t>& waiting_queue,
        const std::unordered_map<uint64_t, SchedulerRequestMeta>& requests) const = 0;

    virtual uint64_t select_preempt_candidate(
        const std::deque<uint64_t>& running_queue,
        const std::unordered_map<uint64_t, SchedulerRequestMeta>& requests,
        uint64_t current_request_id) const = 0;
};

/**
 * @brief First-Come-First-Served policy implementation.
 */
class FcfsSchedulerStrategy final : public SchedulerStrategy {
public:
    void sort_waiting(
        std::deque<uint64_t>& waiting_queue,
        const std::unordered_map<uint64_t, SchedulerRequestMeta>& requests) const override;

    uint64_t select_preempt_candidate(
        const std::deque<uint64_t>& running_queue,
        const std::unordered_map<uint64_t, SchedulerRequestMeta>& requests,
        uint64_t current_request_id) const override;
};

/**
 * @brief Scheduler mechanism with strategy and configuration hooks.
 */
class Scheduler {
public:
    explicit Scheduler(const EngineArgs& args);
    explicit Scheduler(SchedulerConfig config = SchedulerConfig{});
    Scheduler(KVCache* kv, SchedulerConfig config = SchedulerConfig{});

    const SchedulerConfig& config() const { return config_; }
    KVCache* kv_cache() const;

    void add_request(const EngineCoreRequest& request, int32_t vocab_size);
    void abort_request(uint64_t internal_id);
    SchedulerOutput schedule();
    std::map<uint64_t, EngineCoreOutput> update_from_output(
        const SchedulerOutput& scheduler_output,
        const ModelOutput& model_output);
    void post_step();

    SchedulerResult schedule(
        std::deque<uint64_t>& running_queue,
        std::deque<uint64_t>& waiting_queue,
        const std::unordered_map<uint64_t, SchedulerRequestMeta>& requests,
        const std::function<bool(uint64_t)>& can_append_one_token,
        const std::function<bool(uint64_t, int32_t)>& can_allocate_prefill) const;

private:
    int32_t assign_core_seq_id();
    void remove_from_waiting_queue(uint64_t internal_id);
    void remove_from_running_queue(uint64_t internal_id);
    void sync_queues();
    std::unordered_map<uint64_t, SchedulerRequestMeta> build_scheduler_meta() const;
    void validate_schedule_contracts() const;
    CoreSequence* find_sequence(uint64_t internal_id);

    std::unique_ptr<SchedulerStrategy> build_strategy(SchedulerPolicy policy) const;

    SchedulerConfig config_;
    std::unique_ptr<SchedulerStrategy> strategy_;
    std::unique_ptr<BlockManager> block_manager_;
    std::unordered_map<uint64_t, CoreSequence> seqs_;
    std::deque<uint64_t> waiting_queue_;
    std::deque<uint64_t> running_queue_;
    int32_t next_core_seq_id_ = 1;
    uint64_t next_arrival_order_ = 1;
};

} // namespace tiny_llm
